version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    open-pull-requests-limit: 10
    labels: ["dependabot", "dependencies"]
    commit-message:
      prefix: "chore"
    rebase-strategy: "auto"

    groups:
      babel-stack:
        update-types: [minor, patch]
        patterns:
          - "@babel/*"
      eslint-stack:
        update-types: [minor, patch]
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-*"
      all-minor-and-patch:
        update-types: [minor, patch]
        patterns:
          - "*"
      majors:
        update-types: [major]
        patterns:
          - "*"
      minor-and-patch:
        update-types: [minor, patch]
        patterns: ["*"]
      eslint-stack-majors:
        update-types: [major]
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-*"
          - "@typescript-eslint/*"
      babel-stack-majors:
        update-types: [major]
        patterns:
          - "@babel/*"
          - "babel-loader"
      webpack-stack-majors:
        update-types: [major]
        patterns:
          - "webpack"
          - "webpack-cli"
          - "webpack-dev-server"
          - "babel-loader"
          - "css-loader"
          - "style-loader"
          - "file-loader"
          - "url-loader"
